/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CapacitySharingPolicyRangeApplyConfiguration represents a declarative configuration of the CapacitySharingPolicyRange type for use
// with apply.
type CapacitySharingPolicyRangeApplyConfiguration struct {
	Min  *resource.Quantity `json:"min,omitempty"`
	Max  *resource.Quantity `json:"max,omitempty"`
	Step *resource.Quantity `json:"step,omitempty"`
}

// CapacitySharingPolicyRangeApplyConfiguration constructs a declarative configuration of the CapacitySharingPolicyRange type for use with
// apply.
func CapacitySharingPolicyRange() *CapacitySharingPolicyRangeApplyConfiguration {
	return &CapacitySharingPolicyRangeApplyConfiguration{}
}

// WithMin sets the Min field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Min field is set to the value of the last call.
func (b *CapacitySharingPolicyRangeApplyConfiguration) WithMin(value resource.Quantity) *CapacitySharingPolicyRangeApplyConfiguration {
	b.Min = &value
	return b
}

// WithMax sets the Max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Max field is set to the value of the last call.
func (b *CapacitySharingPolicyRangeApplyConfiguration) WithMax(value resource.Quantity) *CapacitySharingPolicyRangeApplyConfiguration {
	b.Max = &value
	return b
}

// WithStep sets the Step field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Step field is set to the value of the last call.
func (b *CapacitySharingPolicyRangeApplyConfiguration) WithStep(value resource.Quantity) *CapacitySharingPolicyRangeApplyConfiguration {
	b.Step = &value
	return b
}
