/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// CapacityClaimPolicyApplyConfiguration represents a declarative configuration of the CapacityClaimPolicy type for use
// with apply.
type CapacityClaimPolicyApplyConfiguration struct {
	Set   *CapacityClaimPolicySetApplyConfiguration   `json:"set,omitempty"`
	Range *CapacityClaimPolicyRangeApplyConfiguration `json:"range,omitempty"`
}

// CapacityClaimPolicyApplyConfiguration constructs a declarative configuration of the CapacityClaimPolicy type for use with
// apply.
func CapacityClaimPolicy() *CapacityClaimPolicyApplyConfiguration {
	return &CapacityClaimPolicyApplyConfiguration{}
}

// WithSet sets the Set field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Set field is set to the value of the last call.
func (b *CapacityClaimPolicyApplyConfiguration) WithSet(value *CapacityClaimPolicySetApplyConfiguration) *CapacityClaimPolicyApplyConfiguration {
	b.Set = value
	return b
}

// WithRange sets the Range field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Range field is set to the value of the last call.
func (b *CapacityClaimPolicyApplyConfiguration) WithRange(value *CapacityClaimPolicyRangeApplyConfiguration) *CapacityClaimPolicyApplyConfiguration {
	b.Range = value
	return b
}
