/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CapacityClaimPolicyRangeApplyConfiguration represents a declarative configuration of the CapacityClaimPolicyRange type for use
// with apply.
type CapacityClaimPolicyRangeApplyConfiguration struct {
	Minimum *resource.Quantity `json:"minimum,omitempty"`
	Maximum *resource.Quantity `json:"maximum,omitempty"`
	Step    *resource.Quantity `json:"step,omitempty"`
}

// CapacityClaimPolicyRangeApplyConfiguration constructs a declarative configuration of the CapacityClaimPolicyRange type for use with
// apply.
func CapacityClaimPolicyRange() *CapacityClaimPolicyRangeApplyConfiguration {
	return &CapacityClaimPolicyRangeApplyConfiguration{}
}

// WithMinimum sets the Minimum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Minimum field is set to the value of the last call.
func (b *CapacityClaimPolicyRangeApplyConfiguration) WithMinimum(value resource.Quantity) *CapacityClaimPolicyRangeApplyConfiguration {
	b.Minimum = &value
	return b
}

// WithMaximum sets the Maximum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maximum field is set to the value of the last call.
func (b *CapacityClaimPolicyRangeApplyConfiguration) WithMaximum(value resource.Quantity) *CapacityClaimPolicyRangeApplyConfiguration {
	b.Maximum = &value
	return b
}

// WithStep sets the Step field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Step field is set to the value of the last call.
func (b *CapacityClaimPolicyRangeApplyConfiguration) WithStep(value resource.Quantity) *CapacityClaimPolicyRangeApplyConfiguration {
	b.Step = &value
	return b
}
