/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CapacitySharingPolicyDiscreteApplyConfiguration represents a declarative configuration of the CapacitySharingPolicyDiscrete type for use
// with apply.
type CapacitySharingPolicyDiscreteApplyConfiguration struct {
	Options []resource.Quantity `json:"options,omitempty"`
}

// CapacitySharingPolicyDiscreteApplyConfiguration constructs a declarative configuration of the CapacitySharingPolicyDiscrete type for use with
// apply.
func CapacitySharingPolicyDiscrete() *CapacitySharingPolicyDiscreteApplyConfiguration {
	return &CapacitySharingPolicyDiscreteApplyConfiguration{}
}

// WithOptions adds the given value to the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Options field.
func (b *CapacitySharingPolicyDiscreteApplyConfiguration) WithOptions(values ...resource.Quantity) *CapacitySharingPolicyDiscreteApplyConfiguration {
	for i := range values {
		b.Options = append(b.Options, values[i])
	}
	return b
}
