/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CapacitySharingPolicyApplyConfiguration represents a declarative configuration of the CapacitySharingPolicy type for use
// with apply.
type CapacitySharingPolicyApplyConfiguration struct {
	Default        *resource.Quantity                               `json:"default,omitempty"`
	DiscreteValues *CapacitySharingPolicyDiscreteApplyConfiguration `json:"discreteValues,omitempty"`
	ValueRange     *CapacitySharingPolicyRangeApplyConfiguration    `json:"valueRange,omitempty"`
}

// CapacitySharingPolicyApplyConfiguration constructs a declarative configuration of the CapacitySharingPolicy type for use with
// apply.
func CapacitySharingPolicy() *CapacitySharingPolicyApplyConfiguration {
	return &CapacitySharingPolicyApplyConfiguration{}
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *CapacitySharingPolicyApplyConfiguration) WithDefault(value resource.Quantity) *CapacitySharingPolicyApplyConfiguration {
	b.Default = &value
	return b
}

// WithDiscreteValues sets the DiscreteValues field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiscreteValues field is set to the value of the last call.
func (b *CapacitySharingPolicyApplyConfiguration) WithDiscreteValues(value *CapacitySharingPolicyDiscreteApplyConfiguration) *CapacitySharingPolicyApplyConfiguration {
	b.DiscreteValues = value
	return b
}

// WithValueRange sets the ValueRange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueRange field is set to the value of the last call.
func (b *CapacitySharingPolicyApplyConfiguration) WithValueRange(value *CapacitySharingPolicyRangeApplyConfiguration) *CapacitySharingPolicyApplyConfiguration {
	b.ValueRange = value
	return b
}
