name: Run e2e tests

on: [ push ]

env:
  VERSION: "1.34"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      KUBE_GIT_VERSION: v1.34.0-alpha.0.2276+6f3400c755b5e1-dirty
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
        chmod +x ./kind
        mv ./kind /usr/local/bin
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build custom KIND node image
      run: |
        kind build node-image --image dra/node:latest $(pwd)
    - name: Bring up Kind Cluster
      run: |
        rm -rf /opt/hostedtoolcache
        kind create cluster --config test/e2e/dra/kind.yaml --image dra/node:latest
    - name: Build ginkgo
      run: |
        make ginkgo
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Add Go bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Run test
      run: |
        KUBECONFIG=~/.kube/config _output/bin/ginkgo -p -v -focus=Feature:DynamicResourceAllocation ./test/e2e
