name: Run full unit tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Test
      run: |
        make test
