name: Run tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up for integration test
      run: |
        ./hack/install-etcd.sh
        echo "PATH=$(pwd)/third_party/etcd:$PATH" >> $GITHUB_ENV
        ulimit -n 1200
    - name: Integration test
      run: |
        make test-integration WHAT=./test/integration/scheduler_perf/... KUBE_TEST_ARGS=-use-testing-log
