name: Run quick unit tests on branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout selected branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Import verify
      run: |
        ./hack/verify-imports.sh
        ./hack/verify-publishing-bot.sh
    - name: Validation test
      run: |
        go test -timeout 30s k8s.io/kubernetes/pkg/apis/resource/validation
    - name: API/Strategy unit test
      run: |
        make test WHAT=./pkg/apis/resource/...  GOFLAGS=-v KUBE_COVER=y
        make test WHAT=./pkg/registry/resource/... GOFLAGS=-v KUBE_COVER=y
        make test WHAT=./pkg/kubelet/cm/dra/... GOFLAGS=-v KUBE_COVER=y
    - name: Allocator unit test
      run: |
        make test WHAT=./staging/src/k8s.io/dynamic-resource-allocation/structured/... GOFLAGS=-v KUBE_COVER=y
