name: Run unit tests

on: [ push ]

env:
  TERM: xterm

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Validation test
      run: |
        go test -timeout 30s k8s.io/kubernetes/pkg/apis/resource/validation
    - name: API/Strategy unit test
      run: |
        make test WHAT=./pkg/apis/resource/...  GOFLAGS=-v KUBE_COVER=y
        make test WHAT=./pkg/registry/resource/... GOFLAGS=-v KUBE_COVER=y
        make test WHAT=./pkg/kubelet/cm/dra/... GOFLAGS=-v KUBE_COVER=y
    - name: Allocator unit test
      run: |
        make test WHAT=./staging/src/k8s.io/dynamic-resource-allocation/structured/... GOFLAGS=-v KUBE_COVER=y
    - name: Verify
      run: |
        rm -rf /opt/hostedtoolcache
        make verify BRANCH=${{ github.ref_name }}
