name: Run tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: API/Strategy unit test
      run: |
        make test WHAT=./pkg/apis/resource/...  GOFLAGS=-v KUBE_COVER=y
        make test WHAT=./pkg/registry/resource/... GOFLAGS=-v KUBE_COVER=y
    - name: Allocator unit test
      run: |
        make test WHAT=./staging/src/k8s.io/dynamic-resource-allocation/structured/... GOFLAGS=-v KUBE_COVER=y
