name: Run verify

on: [ push ]

env:
  TERM: xterm

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4
    - name: Verify
      run: |
        rm -rf /opt/hostedtoolcache
        make verify BRANCH=${{ github.ref_name }}
